Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans: Yes there are differences


In [4]:
print(list_)
print(type(list_))

['1', '2', '3', '4', '5']
<class 'list'>


In [5]:
print(array_list)
print(type(array_list))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans: Yes there is difference. The other one is a string list and the other one is intger list


In [6]:
array_list = np.array(object = list_, dtype = int)


In [8]:
print(list_)
print(type(list_))

print(array_list)
print(type(array_list))



['1', '2', '3', '4', '5']
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [9]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [10]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
num_array.shape

(2, 3)

In [12]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [13]:
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
dimension = int(input("Enter the dimension of identitiy matrix: "))
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

Enter the dimension of identitiy matrix: 5
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
